[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]
aptPkgs = []

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile --prod=false"
]

[phases.build]
cmds = [
  "pnpm build"
]

[start]
cmd = "node apps/api/dist/index.js"

[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_DOWNLOAD = "true"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
